//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loki.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loki.Globalization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowExternalAccess.
        /// </summary>
        public static string AllowExternalAccess {
            get {
                return ResourceManager.GetString("AllowExternalAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthError.
        /// </summary>
        public static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthLogin.
        /// </summary>
        public static string AuthLogin {
            get {
                return ResourceManager.GetString("AuthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthLoginErrorEmpty.
        /// </summary>
        public static string AuthLoginErrorEmpty {
            get {
                return ResourceManager.GetString("AuthLoginErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthLoginInstructions.
        /// </summary>
        public static string AuthLoginInstructions {
            get {
                return ResourceManager.GetString("AuthLoginInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoLogin.
        /// </summary>
        public static string AutoLogin {
            get {
                return ResourceManager.GetString("AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSelectConfig.
        /// </summary>
        public static string AutoSelectConfig {
            get {
                return ResourceManager.GetString("AutoSelectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSelectLanguage.
        /// </summary>
        public static string AutoSelectLanguage {
            get {
                return ResourceManager.GetString("AutoSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        public static string Bot {
            get {
                return ResourceManager.GetString("Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuddyUpdaterError.
        /// </summary>
        public static string BuddyUpdaterError {
            get {
                return ResourceManager.GetString("BuddyUpdaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseConfig.
        /// </summary>
        public static string ChooseConfig {
            get {
                return ResourceManager.GetString("ChooseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseConfigErrorEmpty.
        /// </summary>
        public static string ChooseConfigErrorEmpty {
            get {
                return ResourceManager.GetString("ChooseConfigErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseConfigErrorInvalid.
        /// </summary>
        public static string ChooseConfigErrorInvalid {
            get {
                return ResourceManager.GetString("ChooseConfigErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseLanguage.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmdSettings.
        /// </summary>
        public static string CmdSettings {
            get {
                return ResourceManager.GetString("CmdSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmdSupport.
        /// </summary>
        public static string CmdSupport {
            get {
                return ResourceManager.GetString("CmdSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CmdTools.
        /// </summary>
        public static string CmdTools {
            get {
                return ResourceManager.GetString("CmdTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompileAsynchronously.
        /// </summary>
        public static string CompileAsynchronously {
            get {
                return ResourceManager.GetString("CompileAsynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigInstructions.
        /// </summary>
        public static string ConfigInstructions {
            get {
                return ResourceManager.GetString("ConfigInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigNoBotGui.
        /// </summary>
        public static string ConfigNoBotGui {
            get {
                return ResourceManager.GetString("ConfigNoBotGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigNoPluginGui.
        /// </summary>
        public static string ConfigNoPluginGui {
            get {
                return ResourceManager.GetString("ConfigNoPluginGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigNoRoutineGui.
        /// </summary>
        public static string ConfigNoRoutineGui {
            get {
                return ResourceManager.GetString("ConfigNoRoutineGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentOrder.
        /// </summary>
        public static string ContentOrder {
            get {
                return ResourceManager.GetString("ContentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugLastTask.
        /// </summary>
        public static string DebugLastTask {
            get {
                return ResourceManager.GetString("DebugLastTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableAutoUpdate.
        /// </summary>
        public static string DisableAutoUpdate {
            get {
                return ResourceManager.GetString("DisableAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisabledContent.
        /// </summary>
        public static string DisabledContent {
            get {
                return ResourceManager.GetString("DisabledContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DontAutoFocusBotWindow.
        /// </summary>
        public static string DontAutoFocusBotWindow {
            get {
                return ResourceManager.GetString("DontAutoFocusBotWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DontAutoFocusGameWindow.
        /// </summary>
        public static string DontAutoFocusGameWindow {
            get {
                return ResourceManager.GetString("DontAutoFocusGameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadInstructions.
        /// </summary>
        public static string DownloadInstructions {
            get {
                return ResourceManager.GetString("DownloadInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableOverlay.
        /// </summary>
        public static string EnableOverlay {
            get {
                return ResourceManager.GetString("EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitOnCompileErrors.
        /// </summary>
        public static string ExitOnCompileErrors {
            get {
                return ResourceManager.GetString("ExitOnCompileErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitOnLoadErrors.
        /// </summary>
        public static string ExitOnLoadErrors {
            get {
                return ResourceManager.GetString("ExitOnLoadErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceStopBot.
        /// </summary>
        public static string ForceStopBot {
            get {
                return ResourceManager.GetString("ForceStopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuideLink.
        /// </summary>
        public static string GuideLink {
            get {
                return ResourceManager.GetString("GuideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuideText.
        /// </summary>
        public static string GuideText {
            get {
                return ResourceManager.GetString("GuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageInstructions.
        /// </summary>
        public static string LanguageInstructions {
            get {
                return ResourceManager.GetString("LanguageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogClear.
        /// </summary>
        public static string LogClear {
            get {
                return ResourceManager.GetString("LogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogCopy.
        /// </summary>
        public static string LogCopy {
            get {
                return ResourceManager.GetString("LogCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogFileNameCopied.
        /// </summary>
        public static string LogFileNameCopied {
            get {
                return ResourceManager.GetString("LogFileNameCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogFileZipFail.
        /// </summary>
        public static string LogFileZipFail {
            get {
                return ResourceManager.GetString("LogFileZipFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogFileZipSuccess.
        /// </summary>
        public static string LogFileZipSuccess {
            get {
                return ResourceManager.GetString("LogFileZipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogZip.
        /// </summary>
        public static string LogZip {
            get {
                return ResourceManager.GetString("LogZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoHideOnMinimize.
        /// </summary>
        public static string NoHideOnMinimize {
            get {
                return ResourceManager.GetString("NoHideOnMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformanceLogging.
        /// </summary>
        public static string PerformanceLogging {
            get {
                return ResourceManager.GetString("PerformanceLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginAuthor.
        /// </summary>
        public static string PluginAuthor {
            get {
                return ResourceManager.GetString("PluginAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginConfig.
        /// </summary>
        public static string PluginConfig {
            get {
                return ResourceManager.GetString("PluginConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginDescription.
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginEnable.
        /// </summary>
        public static string PluginEnable {
            get {
                return ResourceManager.GetString("PluginEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginsGlobal.
        /// </summary>
        public static string PluginsGlobal {
            get {
                return ResourceManager.GetString("PluginsGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginVersion.
        /// </summary>
        public static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine.
        /// </summary>
        public static string Routine {
            get {
                return ResourceManager.GetString("Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectProcess.
        /// </summary>
        public static string SelectProcess {
            get {
                return ResourceManager.GetString("SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectProcessActivate.
        /// </summary>
        public static string SelectProcessActivate {
            get {
                return ResourceManager.GetString("SelectProcessActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectProcessChoose.
        /// </summary>
        public static string SelectProcessChoose {
            get {
                return ResourceManager.GetString("SelectProcessChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectProcessRefresh.
        /// </summary>
        public static string SelectProcessRefresh {
            get {
                return ResourceManager.GetString("SelectProcessRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsConfiguration.
        /// </summary>
        public static string SettingsConfiguration {
            get {
                return ResourceManager.GetString("SettingsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsGlobal.
        /// </summary>
        public static string SettingsGlobal {
            get {
                return ResourceManager.GetString("SettingsGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsGui.
        /// </summary>
        public static string SettingsGui {
            get {
                return ResourceManager.GetString("SettingsGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateInfo.
        /// </summary>
        public static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateNewInstallation.
        /// </summary>
        public static string UpdateNewInstallation {
            get {
                return ResourceManager.GetString("UpdateNewInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateNo.
        /// </summary>
        public static string UpdateNo {
            get {
                return ResourceManager.GetString("UpdateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdaterName.
        /// </summary>
        public static string UpdaterName {
            get {
                return ResourceManager.GetString("UpdaterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateYes.
        /// </summary>
        public static string UpdateYes {
            get {
                return ResourceManager.GetString("UpdateYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionUnsupported.
        /// </summary>
        public static string VersionUnsupported {
            get {
                return ResourceManager.GetString("VersionUnsupported", resourceCulture);
            }
        }
    }
}
